import { CategorySlug } from "./category-types";

export interface CategoryManifestEntry {
  name: string;
  parent?: CategorySlug;
  hidden?: boolean;
}

export const CATEGORY_MANIFEST: Record<CategorySlug, CategoryManifestEntry> = {
  haushaltselektronik: {
    name: "Haushaltselektronik",
    parent: "elektroartikel",
    hidden: true,
  },
  computer: { name: "Computer", parent: "elektroartikel" },
  telekommunikation: { name: "Telekommunikation", parent: "elektroartikel" },
  "apple-iphone": { name: "Apple iPhone", parent: "telekommunikation" },
  "samsung-galaxy": { name: "Samsung Galaxy", parent: "telekommunikation" },
  "hifi-audio": { name: "HiFi & Audio", parent: "elektroartikel" },
  "tv-sat": { name: "TV & Sat", parent: "elektroartikel" },
  fotografie: { name: "Fotografie", parent: "elektroartikel" },
  "drucker-scanner": { name: "Drucker & Scanner", parent: "elektroartikel" },
  "gaming-elektrospielzeug": {
    name: "Gaming & Elektrospielzeug",
    parent: "elektroartikel",
  },
  elektroartikel: { name: "Elektroartikel" },
  deals: { name: "Deals" },
  electronics: { name: "Elektronik", hidden: true },
  tvs: { name: "Fernseher", parent: "tv-sat" },
  staubsauger: {
    name: "Staubsauger",
    parent: "haushaltselektronik",
    hidden: true,
  },
  headphones: { name: "Kopfhörer", parent: "hifi-audio" },
  notebooks: { name: "Notebooks", parent: "computer" },
  tablets: { name: "Tablets", parent: "computer" },
  espressomaschinen: {
    name: "Espressomaschinen",
    parent: "haushaltselektronik",
    hidden: true,
  },
  monitors: { name: "Monitore", parent: "computer" },
  speakers: { name: "Lautsprecher", parent: "hifi-audio" },
  kuehlschraenke: {
    name: "Kühlschränke",
    parent: "haushaltselektronik",
    hidden: true,
  },
  "elektrische-zahnbuersten": {
    name: "Elektrische Zahnbürsten",
    parent: "haushaltselektronik",
    hidden: true,
  },
  waschmaschinen: {
    name: "Waschmaschinen",
    parent: "haushaltselektronik",
    hidden: true,
  },
  multifunktionsdrucker: {
    name: "Multifunktionsdrucker",
    parent: "drucker-scanner",
  },
  geschirrspueler: {
    name: "Geschirrspüler",
    parent: "haushaltselektronik",
    hidden: true,
  },
  routers: { name: "Router", parent: "telekommunikation" },
  systemkameras: { name: "Systemkameras", parent: "fotografie" },
  backoefen: { name: "Backöfen", parent: "haushaltselektronik", hidden: true },
  kochfelder: {
    name: "Kochfelder",
    parent: "haushaltselektronik",
    hidden: true,
  },
  soundbars: { name: "Soundbars", parent: "hifi-audio" },
  radios: { name: "Radios", parent: "hifi-audio" },
  waeschetrockner: {
    name: "Wäschetrockner",
    parent: "haushaltselektronik",
    hidden: true,
  },
  kuechenmaschinen: {
    name: "Küchenmaschinen",
    parent: "haushaltselektronik",
    hidden: true,
  },
  "bartschneider-haarschneider": {
    name: "Bartschneider & Haarschneider",
    parent: "haushaltselektronik",
    hidden: true,
  },
  receiver: { name: "Receiver", parent: "hifi-audio" },
  mikrowellen: {
    name: "Mikrowellen",
    parent: "haushaltselektronik",
    hidden: true,
  },
  dunstabzugshauben: {
    name: "Dunstabzugshauben",
    parent: "haushaltselektronik",
    hidden: true,
  },
  "hard-drives": { name: "Festplatten", parent: "pc-komponenten" },
  gefrierschraenke: {
    name: "Gefrierschränke",
    parent: "haushaltselektronik",
    hidden: true,
  },
  herde: { name: "Herde", parent: "haushaltselektronik", hidden: true },
  drones: { name: "Drohnen", parent: "fotografie" },
  nas: { name: "NAS-Server", parent: "computer" },
  "pc-komponenten": { name: "PC-Komponenten", parent: "computer" },
  gpu: { name: "Grafikkarten", parent: "pc-komponenten" },
  motherboards: { name: "Mainboards", parent: "pc-komponenten" },
  ram: { name: "Arbeitsspeicher", parent: "pc-komponenten" },
  "pc-cases": { name: "PC-Gehäuse", parent: "pc-komponenten" },
  "power-supplies": { name: "Netzteile", parent: "pc-komponenten" },
  "cpu-coolers": { name: "CPU-Kühler", parent: "pc-komponenten" },
  storage: { name: "Laufwerke", parent: "pc-komponenten" },
  ssds: { name: "SSDs", parent: "pc-komponenten" },
  "smartwatch-accessories": {
    name: "Smartwatch-Zubehör",
    parent: "telekommunikation",
  },
  smartphones: { name: "Smartphones", parent: "telekommunikation" },
  smartwatches: { name: "Smartwatches", parent: "telekommunikation" },
  consoles: { name: "Spielekonsolen", parent: "gaming-elektrospielzeug" },
  cameras: { name: "Digitalkameras", parent: "fotografie" },
  keyboards: { name: "Tastaturen", parent: "computer" },
  mice: { name: "Mäuse", parent: "computer" },
  "mouse-pads": { name: "Mauspads", parent: "computer" },
  "external-storage": { name: "Externe Speicher", parent: "computer" },
  speicherkarten: { name: "Speicherkarten", parent: "fotografie" },
  "docking-stations": { name: "Docking-Stationen", parent: "computer" },
  "network-switches": {
    name: "Netzwerk-Switches",
    parent: "telekommunikation",
  },
  "network-cards": { name: "Netzwerkkarten", parent: "pc-komponenten" },
  cables: { name: "Kabel & Adapter", parent: "elektroartikel" },
  "laptop-stands": { name: "Laptop-Ständer", parent: "computer" },
  ups: { name: "USV", parent: "pc-komponenten" },
  "cable-management": { name: "Kabelmanagement", parent: "pc-komponenten" },
  "monitor-arms": { name: "Monitorhalterungen", parent: "computer" },
  "desk-accessories": { name: "Schreibtisch-Zubehör", parent: "computer" },
  "office-chairs": { name: "Bürostühle", parent: "computer" },
  "standing-desks": { name: "Stehschreibtische", parent: "computer" },
  "tablet-accessories": { name: "Tablet-Zubehör", parent: "computer" },
  "phone-accessories": { name: "Handy-Zubehör", parent: "telekommunikation" },
  "game-controllers": {
    name: "Game-Controller",
    parent: "gaming-elektrospielzeug",
  },
  "vr-headsets": { name: "VR-Brillen", parent: "gaming-elektrospielzeug" },
  microphones: { name: "Mikrofone", parent: "hifi-audio" },
  "gaming-chairs": { name: "Gaming-Stühle", parent: "gaming-elektrospielzeug" },
  webcams: { name: "Webcams", parent: "computer" },
  "capture-cards": { name: "Capture-Karten", parent: "pc-komponenten" },
  cpu: { name: "Prozessoren", parent: "pc-komponenten" },
  elektrowerkzeuge: {
    name: "Elektrowerkzeuge",
    hidden: true,
    parent: "elektroartikel",
  },
  akkuschrauber: {
    name: "Akkuschrauber",
    hidden: true,
    parent: "elektrowerkzeuge",
  },
  bohrmaschinen: {
    name: "Bohrmaschinen",
    hidden: true,
    parent: "elektrowerkzeuge",
  },
  kreissaegen: { name: "Kreissägen", hidden: true, parent: "elektrowerkzeuge" },
  schleifmaschinen: {
    name: "Schleifmaschinen",
    hidden: true,
    parent: "elektrowerkzeuge",
  },
  fraesmaschinen: {
    name: "Fräsmaschinen",
    hidden: true,
    parent: "elektrowerkzeuge",
  },
  "3d-drucker": { name: "3D-Drucker", parent: "computer" },
  laserdrucker: { name: "Laserdrucker", parent: "drucker-scanner" },
  kompaktkameras: { name: "Kompaktkameras", parent: "fotografie" },
};
