import {
  Armchair,
  Battery,
  Cable,
  Camera,
  Cpu,
  Fan,
  Gamepad2,
  Glasses,
  HardDrive,
  Headphones,
  Home,
  Keyboard,
  Laptop,
  MemoryStick,
  Mic,
  Monitor,
  MonitorCheck,
  Mouse,
  Network,
  Package,
  Phone,
  Printer,
  Router,
  Server,
  Smartphone,
  Speaker,
  Tablet,
  Thermometer,
  Tv,
  Usb,
  Video,
  Watch,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { CategorySlug } from "./category-types";

export const CATEGORY_ICONS: Record<CategorySlug, LucideIcon> = {
  haushaltselektronik: Home,
  computer: Laptop,
  telekommunikation: Phone,
  "apple-iphone": Smartphone,
  "samsung-galaxy": Smartphone,
  "hifi-audio": Speaker,
  "tv-sat": Tv,
  fotografie: Camera,
  "drucker-scanner": Printer,
  "gaming-elektrospielzeug": Gamepad2,
  elektroartikel: Smartphone,
  deals: Zap, // Using Zap for deals icon
  electronics: HardDrive,
  tvs: Tv,
  staubsauger: Fan,
  headphones: Headphones,
  notebooks: Laptop,
  tablets: Tablet,
  espressomaschinen: Zap,
  monitors: Monitor,
  speakers: Speaker,
  kuehlschraenke: Thermometer,
  "elektrische-zahnbuersten": Zap,
  waschmaschinen: Zap,
  multifunktionsdrucker: Printer,
  geschirrspueler: HardDrive,
  routers: Router,
  systemkameras: Camera,
  backoefen: Zap,
  kochfelder: Zap,
  soundbars: Speaker,
  radios: Mic,
  waeschetrockner: Fan,
  kuechenmaschinen: Zap,
  "bartschneider-haarschneider": Zap,
  receiver: Speaker,
  mikrowellen: Zap,
  dunstabzugshauben: Fan,
  "hard-drives": HardDrive,
  gefrierschraenke: Thermometer,
  herde: Zap,
  drones: Camera,
  nas: Server,
  "pc-komponenten": Cpu,
  gpu: Video,
  motherboards: Server,
  ram: MemoryStick,
  "pc-cases": Server,
  "power-supplies": Zap,
  "cpu-coolers": Fan,
  storage: HardDrive,
  ssds: HardDrive,
  "smartwatch-accessories": Watch,
  smartphones: Smartphone,
  smartwatches: Watch,
  consoles: Gamepad2,
  games: Gamepad2,
  cameras: Camera,
  keyboards: Keyboard,
  mice: Mouse,
  "mouse-pads": Mouse,
  "external-storage": HardDrive,
  speicherkarten: MemoryStick,
  "docking-stations": Usb,
  "network-switches": Network,
  "network-cards": Network,
  cables: Cable,
  "laptop-stands": Laptop,
  ups: Battery,
  "cable-management": Cable,
  "monitor-arms": MonitorCheck,
  "desk-accessories": Package,
  "office-chairs": Armchair,
  "standing-desks": Monitor,
  "tablet-accessories": Tablet,
  "phone-accessories": Smartphone,
  "game-controllers": Gamepad2,
  "vr-headsets": Glasses,
  microphones: Mic,
  "gaming-chairs": Armchair,
  webcams: Camera,
  "capture-cards": Video,
  cpu: Cpu,
  elektrowerkzeuge: Zap,
  akkuschrauber: Zap,
  bohrmaschinen: Zap,
  kreissaegen: Zap,
  schleifmaschinen: Zap,
  fraesmaschinen: Zap,
  "3d-drucker": Printer,
  laserdrucker: Printer,
  kompaktkameras: Camera,
};

/**
 * Helper to get an icon for a category slug with a fallback
 */
export function getCategoryIcon(slug: string) {
  return CATEGORY_ICONS[slug as CategorySlug] || Smartphone;
}
