import { CATEGORY_MANIFEST } from "./category-manifest";
import { CategoryData, CategorySlug } from "./category-types";
import { BRAND_DOMAIN } from "./site-config";

export const CATEGORY_MAP: Record<CategorySlug, CategoryData> = {
  haushaltselektronik: {
    ...CATEGORY_MANIFEST.haushaltselektronik,
    description: "Kühlschränke, Waschmaschinen und Küchengeräte",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/household-electronics.jpg",
    popularFilters: [
      { label: "Kühlschränke", href: "/kuehlschraenke" },
      { label: "Waschmaschinen", href: "/waschmaschinen" },
      { label: "Espressomaschinen", href: "/espressomaschinen" },
      { label: "Staubsauger", href: "/staubsauger" },
      { label: "Backöfen", href: "/backoefen" },
    ],
  },
  computer: {
    ...CATEGORY_MANIFEST.computer,
    description: "Notebooks, Monitore, Tablets und Zubehör",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/pc-case.jpg",
    popularFilters: [
      { label: "PC-Komponenten", href: "/pc-komponenten" },
      { label: "Notebooks", href: "/notebooks" },
      { label: "Tablets", href: "/tablets" },
      { label: "Tastaturen", href: "/tastaturen" },
      { label: "Grafikkarten", href: "/grafikkarten" },
    ],
    metaTitle: `Computer & Zubehör Preisvergleich | ${BRAND_DOMAIN}`,
    metaDescription:
      "Vergleichen Sie Preise für Laptops, Monitore und Computer-Zubehör.",
  },
  telekommunikation: {
    ...CATEGORY_MANIFEST.telekommunikation,
    description: "Smartphones, Smartwatches und Zubehör",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/smartphone.jpg",
    popularFilters: [
      { label: "Handys & Smartphones", href: "/smartphones" },
      { label: "Apple iPhone", href: "/smartphones?brand=Apple" },
      { label: "Samsung Galaxy", href: "/smartphones?brand=Samsung" },
      { label: "Google Pixel", href: "/smartphones?brand=Google" },
      { label: "Xiaomi", href: "/smartphones?brand=Xiaomi" },
      { label: "Smartwatches", href: "/smartwatches" },
    ],
  },
  "apple-iphone": {
    name: "Apple iPhone",
    description: "Alle iPhone Modelle im Preisvergleich",
    parent: "telekommunikation",
    categoryType: "standard",
    imageUrl: "/images/category/iphone.jpg",
    popularFilters: [
      { label: "iPhone 15", params: "model=iphone-15" },
      { label: "iPhone 15 Pro", params: "model=iphone-15-pro" },
      { label: "iPhone 14", params: "model=iphone-14" },
    ],
  },
  "samsung-galaxy": {
    name: "Samsung Galaxy",
    description: "Galaxy S, Z und A Serie",
    parent: "telekommunikation",
    categoryType: "standard",
    imageUrl: "/images/category/galaxy.jpg",
    popularFilters: [
      { label: "Galaxy S24", params: "model=s24" },
      { label: "Galaxy Z Fold", params: "series=z-fold" },
      { label: "Galaxy A55", params: "model=a55" },
    ],
  },
  "hifi-audio": {
    name: "HiFi & Audio",
    description: "Kopfhörer, Lautsprecher und Soundbars",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/headphone.jpg",
    popularFilters: [
      { label: "Receiver", href: "/av-receiver" },
      { label: "Kopfhörer", href: "/kopfhoerer" },
      { label: "Lautsprecher", href: "/lautsprecher" },
      { label: "Soundbars", href: "/soundbars" },
      { label: "Radios", href: "/radios" },
    ],
  },
  "tv-sat": {
    name: "TV & Sat",
    description: "Fernseher, Heimkino und Zubehör",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/tv.jpg",
    popularFilters: [
      { label: "Fernseher", href: "/fernseher" },
      { label: "Soundbars", href: "/soundbars" },
      { label: "Receiver", href: "/av-receiver" },
    ],
  },
  fotografie: {
    name: "Fotografie",
    description: "Kameras, Objektive und Zubehör",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/camera.jpg",
    popularFilters: [
      { label: "Systemkameras", href: "/systemkameras" },
      { label: "Digitalkameras", href: "/digitalkameras" },
      { label: "Kompaktkameras", href: "/kompaktkameras" },
      { label: "Speicherkarten", href: "/speicherkarten" },
    ],
  },
  "drucker-scanner": {
    name: "Drucker & Scanner",
    description: "Multifunktionsdrucker, Tinte und Toner",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/printer.jpg",
    popularFilters: [
      { label: "Multifunktionsdrucker", href: "/multifunktionsdrucker" },
      { label: "Laserdrucker", href: "/laserdrucker" },
      { label: "3D-Drucker", href: "/3d-drucker" },
    ],
  },
  "gaming-elektrospielzeug": {
    name: "Gaming & Elektrospielzeug",
    description: "Konsolen, Drohnen und E-Spielzeuge",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/drone.jpg",
    popularFilters: [
      { label: "Spielekonsolen", href: "/spielekonsolen" },
      { label: "Drohnen", href: "/drohnen" },
      { label: "VR-Brillen", href: "/vr-brillen" },
      { label: "Gaming-Stühle", href: "/gaming-stuehle" },
      { label: "Game-Controller", href: "/gamepad-controller" },
    ],
  },
  elektroartikel: {
    name: "Elektroartikel",
    description: "Smartphones, TVs, Kopfhörer und Wearables",
    categoryType: "standard",
    metaTitle: `Elektroartikel & Multimedia Preisvergleich | ${BRAND_DOMAIN}`,
    metaDescription:
      "Top-Angebote für Smartphones, Fernseher und Unterhaltungselektronik.",
  },
  deals: {
    name: "Deals",
    description: "Die besten Angebote und Schnäppchen",
    categoryType: "standard",
    metaTitle: `Deals & Angebote | ${BRAND_DOMAIN}`,
    metaDescription: "Täglich neue Deals und Angebote aus allen Kategorien.",
  },
  electronics: {
    name: "Elektronik",
    description: "Hardware, Computer & Multimedia",
    hidden: true,
    categoryType: "standard",
  },
  fernseher: {
    ...CATEGORY_MANIFEST.fernseher,
    description: "OLED, QLED und Smart TVs",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/tv.jpg",
    aliases: ["tvs"],
    popularFilters: [
      { label: "55 Zoll", params: "size=55" },
      { label: "65 Zoll", params: "size=65" },
      { label: "OLED", params: "panel=oled" },
      { label: "Samsung", params: "brand=Samsung" },
      { label: "LG", params: "brand=LG" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Panel-Technologie", field: "technology", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  staubsauger: {
    name: "Staubsauger",
    description: "Akku-Staubsauger und Saugroboter",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/vacuum-cleaner.jpg",
    hidden: true,
    popularFilters: [
      { label: "Dyson", params: "brand=Dyson" },
      { label: "Saugroboter", params: "type=robot" },
      { label: "Akku-Staubsauger", params: "type=cordless" },
      { label: "Miele", params: "brand=Miele" },
    ],
  },
  kopfhoerer: {
    ...CATEGORY_MANIFEST.kopfhoerer,
    description: "In-Ear, Over-Ear und Bluetooth Kopfhörer",
    categoryType: "standard",
    imageUrl: "/images/category/headphone.jpg",
    aliases: ["headphones"],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Technologie", field: "technology", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  notebooks: {
    name: "Notebooks",
    description: "Laptops, MacBooks und Convertibles",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/notebook.jpg",
    aliases: ["laptops"],
    popularFilters: [
      { label: "Apple MacBook", params: "brand=Apple" },
      { label: "Gaming Laptops", params: "type=gaming" },
      { label: "16 GB RAM", params: "ram=16" },
      { label: "Intel Core Ultra", params: "cpu=intel-ultra" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  tablets: {
    name: "Tablets",
    description: "iPads und Android Tablets",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/tablet.jpg",
    popularFilters: [
      { label: "Apple iPad", params: "brand=Apple" },
      { label: "Samsung Galaxy Tab", params: "brand=Samsung" },
      { label: "Android-Tablet", params: "os=android" },
      { label: "5G-Tablet", params: "connectivity=5g" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  espressomaschinen: {
    name: "Espressomaschinen",
    description: "Kaffeevollautomaten und Siebträgermaschinen",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/espresso-machine.jpg",
    hidden: true,
    popularFilters: [
      { label: "Kaffeevollautomat", params: "type=fully-automatic" },
      { label: "Siebträgermaschine", params: "type=portafilter" },
      { label: "De'Longhi", params: "brand=delonghi" },
      { label: "Siemens EQ.6", params: "model=eq6" },
    ],
  },
  monitore: {
    ...CATEGORY_MANIFEST.monitore,
    description: "Gaming und Office Monitore",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/monitor.jpg",
    aliases: ["bildschirme", "screens", "monitors"],
    popularFilters: [
      { label: "27 Zoll", params: "size=27" },
      { label: "144 Hz", params: "refresh=144" },
      { label: "4K Monitor", params: "resolution=4k" },
      { label: "Gaming Monitor", params: "type=gaming" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  lautsprecher: {
    ...CATEGORY_MANIFEST.lautsprecher,
    description: "Bluetooth, Regal und Standlautsprecher",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/speakers.jpg",
    aliases: ["speakers"],
    popularFilters: [
      { label: "JBL", params: "brand=jbl" },
      { label: "Sonos", params: "brand=sonos" },
      { label: "Bluetooth Lautsprecher", params: "type=bluetooth" },
      { label: "Subwoofer", params: "type=subwoofer" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  kuehlschraenke: {
    name: "Kühlschränke",
    description: "Kühl-Gefrierkombinationen und Side-by-Side",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/refrigerator.jpg",
    hidden: true,
    popularFilters: [
      { label: "Bosch", params: "brand=bosch" },
      { label: "Liebherr", params: "brand=liebherr" },
      { label: "Einbaukühlschrank", params: "type=built-in" },
      { label: "Side-by-Side", params: "type=side-by-side" },
    ],
  },
  "elektrische-zahnbuersten": {
    name: "Elektrische Zahnbürsten",
    description: "Schall- und oszillierende Zahnbürsten",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/electric-toothbrush.jpg",
    hidden: true,
    popularFilters: [
      { label: "Oral-B iO", params: "model=io" },
      { label: "Philips Sonicare", params: "model=sonicare" },
      { label: "Schallzahnbürste", params: "type=sonic" },
    ],
  },
  waschmaschinen: {
    name: "Waschmaschinen",
    description: "Frontlader und Toplader",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/washing-machine.jpg",
    hidden: true,
    popularFilters: [
      { label: "Miele", params: "brand=miele" },
      { label: "Bosch", params: "brand=bosch" },
      { label: "9 kg", params: "capacity=9" },
      { label: "Frontlader", params: "type=front-loader" },
    ],
  },
  multifunktionsdrucker: {
    name: "Multifunktionsdrucker",
    description: "Drucken, Scannen und Kopieren",
    parent: "drucker-scanner",
    categoryType: "standard",
    imageUrl: "/images/category/printer.jpg",
    popularFilters: [
      { label: "Canon", params: "brand=Canon" },
      { label: "HP", params: "brand=HP" },
      { label: "EcoTank", params: "series=ecotank" },
    ],
  },
  geschirrspueler: {
    name: "Geschirrspüler",
    description: "Einbau- und Standgeschirrspüler",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/dishwasher.jpg",
    hidden: true,
    popularFilters: [
      { label: "Bosch", params: "brand=Bosch" },
      { label: "Miele", params: "brand=Miele" },
      { label: "Vollintegriert", params: "type=integrated" },
    ],
  },
  "wlan-router": {
    ...CATEGORY_MANIFEST["wlan-router"],
    description: "WLAN & Internet Router",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/router.jpg",
    aliases: ["routers"],
    popularFilters: [
      { label: "AVM Fritz!Box", params: "brand=AVM" },
      { label: "WiFi 6", params: "standard=wifi-6" },
      { label: "TP-Link", params: "brand=TP-Link" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Technologie", field: "technology", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  systemkameras: {
    name: "Systemkameras",
    description: "Spiegellose Profikameras",
    parent: "fotografie",
    categoryType: "standard",
    imageUrl: "/images/category/camera.jpg",
    popularFilters: [
      { label: "Nikon", params: "brand=Nikon" },
      { label: "Sony", params: "brand=Sony" },
      { label: "Panasonic", params: "brand=Panasonic" },
      { label: "Fujifilm", params: "brand=Fujifilm" },
      { label: "Vollformat", params: "sensor=Full+Frame" },
      { label: "APS-C", params: "sensor=APS-C" },
    ],
  },
  backoefen: {
    name: "Backöfen",
    description: "Einbaubacköfen und Sets",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/oven.jpg",
    hidden: true,
    popularFilters: [
      { label: "Bosch", params: "brand=Bosch" },
      { label: "Siemens", params: "brand=Siemens" },
      { label: "Pyrolyse", params: "features=pyrolysis" },
    ],
  },
  kochfelder: {
    name: "Kochfelder",
    description: "Induktion, Ceran und Gas",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/cooktop.jpg",
    hidden: true,
    popularFilters: [
      { label: "Induktion", params: "type=induction" },
      { label: "Kochfeldabzug", params: "features=extractor" },
      { label: "80 cm breit", params: "width=80" },
    ],
  },
  soundbars: {
    name: "Soundbars",
    description: "Heimkino-Soundsysteme",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/soundbar.jpg",
    popularFilters: [
      { label: "Sonos", params: "brand=Sonos" },
      { label: "Samsung", params: "brand=Samsung" },
      { label: "Dolby Atmos", params: "features=atmos" },
    ],
  },
  radios: {
    name: "Radios",
    description: "DAB+, Internet- und Kurbelradios",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/radio.jpg",
    popularFilters: [
      { label: "DAB+", params: "type=dab-plus" },
      { label: "Internetradio", params: "type=internet" },
      { label: "TechniSat", params: "brand=TechniSat" },
    ],
  },
  waeschetrockner: {
    name: "Wäschetrockner",
    description: "Wärmepumpen- und Kondenstrockner",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/clothes-dryer.jpg",
    hidden: true,
    popularFilters: [
      { label: "Wärmepumpentrockner", params: "type=heat-pump" },
      { label: "Miele", params: "brand=Miele" },
      { label: "AEG", params: "brand=AEG" },
    ],
  },
  kuechenmaschinen: {
    name: "Küchenmaschinen",
    description: "Knet- und Multifunktionsmaschinen",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/kitchen-machine.jpg",
    hidden: true,
    popularFilters: [
      { label: "KitchenAid", params: "brand=KitchenAid" },
      { label: "Bosch MUM", params: "series=mum" },
      { label: "Thermomix", params: "brand=Vorwerk" },
    ],
  },
  "bartschneider-haarschneider": {
    name: "Bartschneider & Haarschneider",
    description: "Haarpflege für Männer",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/beard-trimmer.jpg",
    hidden: true,
    popularFilters: [
      { label: "Philips OneBlade", params: "model=oneblade" },
      { label: "Braun", params: "brand=Braun" },
      { label: "Haarschneider", params: "type=hair" },
    ],
  },
  "av-receiver": {
    ...CATEGORY_MANIFEST["av-receiver"],
    description: "AV-Receiver und Verstärker",
    parent: "elektroartikel",
    categoryType: "standard",
    aliases: ["receiver"],
    popularFilters: [
      { label: "AV-Receiver", params: "type=av" },
      { label: "Yamaha", params: "brand=Yamaha" },
      { label: "Denon", params: "brand=Denon" },
      { label: "Marantz", params: "brand=Marantz" },
      { label: "7.2 Kanal", params: "channels=7.2" },
    ],
  },
  mikrowellen: {
    name: "Mikrowellen",
    description: "Stand- und Einbaumikrowellen",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/microwave.jpg",
    hidden: true,
    popularFilters: [
      { label: "Einbau-Mikrowelle", params: "type=built-in" },
      { label: "Samsung", params: "brand=Samsung" },
    ],
  },
  dunstabzugshauben: {
    name: "Dunstabzugshauben",
    description: "Wand-, Insel- und Unterbauhauben",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/cooker-hood.jpg",
    hidden: true,
    popularFilters: [
      { label: "Kopffreihaube", params: "type=angled" },
      { label: "60 cm breit", params: "width=60" },
    ],
  },
  festplatten: {
    ...CATEGORY_MANIFEST.festplatten,
    description: "HDD Speicherlösungen",
    parent: "elektroartikel",
    categoryType: "analytical",
    imageUrl: "/images/category/hdd.jpg",
    aliases: ["hdd", "hard-drives"],
    unitType: "TB",
    unitLabel: "pro TB",
    popularFilters: [
      { label: "4 TB", params: "capacity=4" },
      { label: "NAS-Festplatte", params: "type=nas" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Kapazität", field: "capacity", type: "checkbox" },
      { label: "Formfaktor", field: "formFactor", type: "checkbox" },
      { label: "Technologie", field: "technology", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  gefrierschraenke: {
    name: "Gefrierschränke",
    description: "Gefrierschränke und Truhen",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/freezer.jpg",
    hidden: true,
    popularFilters: [
      { label: "Liebherr", params: "brand=Liebherr" },
      { label: "NoFrost", params: "features=nofrost" },
    ],
  },
  herde: {
    name: "Herde",
    description: "Stand- und Einbauherde",
    parent: "elektroartikel",
    categoryType: "standard",
    imageUrl: "/images/category/stove.jpg",
    hidden: true,
    popularFilters: [
      { label: "Induktionsherd", params: "type=induction" },
      { label: "Herd-Set", params: "type=set" },
    ],
  },
  drohnen: {
    ...CATEGORY_MANIFEST.drohnen,
    description: "Kameradrohnen and Quadcopters",
    parent: "gaming-elektrospielzeug",
    categoryType: "standard",
    imageUrl: "/images/category/drone.jpg",
    popularFilters: [
      { label: "DJI Mini", params: "series=mini" },
      { label: "4K Kamera", params: "resolution=4k" },
    ],
  },
  "nas-systeme": {
    ...CATEGORY_MANIFEST["nas-systeme"],
    description: "Netzwerkspeicher für zuhause",
    parent: "elektroartikel",
    categoryType: "standard",
    aliases: ["nas"],
    popularFilters: [
      { label: "Synology", params: "brand=Synology" },
      { label: "4-Bay NAS", params: "bays=4" },
    ],
  },
  "pc-komponenten": {
    name: "PC-Komponenten",
    description: "Hardware für Ihren PC",
    parent: "computer",
    categoryType: "standard",
    imageUrl: "/images/category/festplatten-&-ssds.jpg",
    popularFilters: [
      { label: "Grafikkarten", href: "/grafikkarten" },
      { label: "Laufwerke", href: "/laufwerke" },
      { label: "Arbeitsspeicher", href: "/arbeitsspeicher" },
      { label: "Prozessoren", href: "/prozessoren" },
      { label: "PC-Gehäuse", href: "/pc-gehaeuse" },
    ],
  },
  grafikkarten: {
    ...CATEGORY_MANIFEST.grafikkarten,
    description: "NVIDIA, AMD & Intel GPUs vergleichen",
    parent: "pc-komponenten",
    categoryType: "analytical",
    imageUrl: "/images/category/gpu.jpg",
    aliases: ["gpu", "graphics-cards"],
    unitType: "GB",
    unitLabel: "pro GB VRAM",
    popularFilters: [
      { label: "RTX 4070", params: "model=RTX+4070" },
      { label: "RTX 4080", params: "model=RTX+4080" },
      { label: "RX 7800 XT", params: "model=RX+7800+XT" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "VRAM", field: "capacity", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  mainboards: {
    ...CATEGORY_MANIFEST.mainboards,
    description: "Motherboards für Intel & AMD",
    parent: "pc-komponenten",
    categoryType: "standard",
    imageUrl: "/images/category/mainboard.jpg",
    aliases: ["motherboards"],
    popularFilters: [
      { label: "AM5 Mainboards", params: "socket=AM5" },
      { label: "LGA 1700", params: "socket=LGA1700" },
      { label: "B650 Chipsatz", params: "chipset=B650" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Sockel", field: "socket", type: "checkbox" },
      { label: "Formfaktor", field: "formFactor", type: "checkbox" },
    ],
  },
  arbeitsspeicher: {
    ...CATEGORY_MANIFEST.arbeitsspeicher,
    description: "DDR4 & DDR5 RAM Module",
    parent: "pc-komponenten",
    categoryType: "analytical",
    imageUrl: "/images/category/ram.jpg",
    aliases: ["ram", "memory"],
    unitType: "GB",
    unitLabel: "pro GB",
    popularFilters: [
      { label: "DDR5 RAM", params: "type=DDR5" },
      { label: "32GB Kits", params: "capacity=32" },
      { label: "6000 MHz", params: "speed=6000" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Kapazität", field: "capacity", type: "checkbox" },
      { label: "Technologie", field: "technology", type: "checkbox" },
    ],
  },
  "pc-gehaeuse": {
    ...CATEGORY_MANIFEST["pc-gehaeuse"],
    description: "Computergehäuse für Ihren Build",
    parent: "pc-komponenten",
    categoryType: "standard",
    imageUrl: "/images/category/pc-case.jpg",
    aliases: ["gehaeuse", "pc-gehaeuse", "cases", "pc-cases"],
    popularFilters: [
      { label: "Midi-Tower", params: "type=midi-tower" },
      { label: "Big-Tower", params: "type=big-tower" },
      { label: "Mini-ITX Gehäuse", params: "type=mini-itx" },
    ],
  },
  netzteile: {
    ...CATEGORY_MANIFEST.netzteile,
    description: "Effiziente Stromversorgung",
    parent: "pc-komponenten",
    categoryType: "analytical",
    imageUrl: "/images/category/power-supply.jpg",
    aliases: ["power-supplies", "psu"],
    unitType: "W",
    unitLabel: "pro Watt",
    popularFilters: [
      { label: "80 PLUS Gold", params: "efficiency=gold" },
      { label: "750 Watt", params: "wattage=750" },
      { label: "Vollmodular", params: "modularity=full" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Leistung", field: "capacity", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  "cpu-kuehler": {
    ...CATEGORY_MANIFEST["cpu-kuehler"],
    description: "Luft- & Wasserkühlung",
    parent: "pc-komponenten",
    categoryType: "standard",
    imageUrl: "/images/category/cpu-cooler.jpg",
    aliases: ["kuehler", "cpu-kuehler", "coolers", "cpu-coolers"],
    popularFilters: [
      { label: "Luftkühler", params: "type=air" },
      { label: "Wasserkühlung (AiO)", params: "type=aio" },
    ],
  },
  laufwerke: {
    ...CATEGORY_MANIFEST.laufwerke,
    description: "Interne & externe Speicherlösungen",
    parent: "pc-komponenten",
    categoryType: "standard",
    imageUrl: "images/category/ssd.jpg",
    aliases: ["storage", "drives"],
    popularFilters: [
      { label: "SSDs", href: "/ssds" },
      { label: "Festplatten (HDD)", href: "/festplatten" },
      { label: "Externe Festplatten", href: "/externe-speicher" },
    ],
  },
  ssds: {
    name: "SSDs",
    description: "Schnelle Solid State Drives",
    parent: "elektroartikel",
    categoryType: "analytical",
    imageUrl: "/images/category/ssd.jpg",
    aliases: ["ssd", "solid-state-drives"],
    unitType: "TB",
    unitLabel: "pro TB",
    popularFilters: [
      { label: "M.2 SSDs (NVMe)", params: "interface=m2-nvme" },
      { label: "SATA SSDs", params: "interface=sata" },
      { label: "PS5 SSDs", params: "compatible=ps5" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Kapazität", field: "capacity", type: "checkbox" },
      { label: "Formfaktor", field: "formFactor", type: "checkbox" },
      { label: "Technologie", field: "technology", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  "smartwatch-zubehoer": {
    ...CATEGORY_MANIFEST["smartwatch-zubehoer"],
    description: "Bänder & Ladestationen",
    parent: "telekommunikation",
    categoryType: "standard",
    imageUrl: "/images/category/smartwatch-accessories.jpg",
    aliases: ["smartwatch-accessories"],
  },
  smartphones: {
    name: "Smartphones",
    description: "Handys & Smartphones",
    parent: "telekommunikation",
    categoryType: "standard",
    imageUrl: "/images/category/smartphone.jpg",
    popularFilters: [
      { label: "iPhone", params: "brand=Apple" },
      { label: "Samsung Galaxy", params: "brand=Samsung" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  smartwatches: {
    name: "Smartwatches",
    description: "Wearables & Watches",
    parent: "telekommunikation",
    categoryType: "standard",
    imageUrl: "/images/category/smartwatch.jpg",
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Zustand", field: "condition", type: "checkbox" },
    ],
  },
  spielekonsolen: {
    ...CATEGORY_MANIFEST.spielekonsolen,
    description: "PS5, Xbox, Switch",
    parent: "gaming-elektrospielzeug",
    categoryType: "standard",
    imageUrl: "/images/category/console.jpg",
    aliases: ["consoles"],
    popularFilters: [
      { label: "Spielekonsolen", href: "/spielekonsolen" },
      { label: "Drohnen", href: "/drohnen" },
      { label: "VR-Brillen", href: "/vr-brillen" },
      { label: "Gaming-Stühle", href: "/gaming-stuehle" },
      { label: "Game-Controller", href: "/gamepad-controller" },
    ],
  },
  videospiele: {
    ...CATEGORY_MANIFEST.videospiele,
    description: "Videospiele für alle Plattformen",
    categoryType: "standard",
    aliases: ["games"],
  },
  digitalkameras: {
    ...CATEGORY_MANIFEST.digitalkameras,
    description: "Kameras & Optik",
    parent: "fotografie",
    categoryType: "standard",
    imageUrl: "/images/category/camera.jpg",
    aliases: ["cameras"],
    popularFilters: [
      { label: "Canon", params: "brand=Canon" },
      { label: "Fujifilm", params: "brand=Fujifilm" },
      { label: "Sony", params: "brand=Sony" },
      { label: "Nikon", params: "brand=Nikon" },
      { label: "Vollformat", params: "sensor=Full+Frame" },
    ],
  },
  tastaturen: {
    ...CATEGORY_MANIFEST.tastaturen,
    description: "Keyboards & Eingabegeräte",
    parent: "computer",
    categoryType: "standard",
    imageUrl: "/images/category/keyboard.jpg",
    aliases: ["keyboards"],
  },
  maeuse: {
    ...CATEGORY_MANIFEST.maeuse,
    description: "Präzisionsmäuse",
    parent: "computer",
    categoryType: "standard",
    imageUrl: "/images/category/mouse.jpg",
    aliases: ["mice", "maus"],
  },
  mauspads: {
    ...CATEGORY_MANIFEST.mauspads,
    description: "Unterlagen",
    parent: "computer",
    categoryType: "standard",
    imageUrl: "/images/category/mouse-pad.jpg",
    aliases: ["mouse-pads"],
  },
  "externe-speicher": {
    ...CATEGORY_MANIFEST["externe-speicher"],
    description: "Portable HDDs & SSDs",
    parent: "laufwerke",
    categoryType: "analytical",
    unitType: "TB",
    unitLabel: "pro TB",
    imageUrl: "/images/category/external-storage.jpg",
    aliases: ["external-storage"],
  },
  speicherkarten: {
    name: "Speicherkarten",
    description: "SD, microSD & CFexpress",
    parent: "fotografie",
    categoryType: "analytical",
    imageUrl: "/images/category/sd-card.jpg",
    unitType: "GB",
    unitLabel: "pro GB",
    popularFilters: [
      { label: "microSDXC", params: "form=microSDXC" },
      { label: "SanDisk", params: "brand=SanDisk" },
      { label: "Samsung", params: "brand=Samsung" },
    ],
  },
  dockingstationen: {
    ...CATEGORY_MANIFEST.dockingstationen,
    description: "Laptop-Docks",
    parent: "computer",
    categoryType: "standard",
    imageUrl: "/images/category/docking-station.jpg",
    aliases: ["docking-stations"],
  },
  "netzwerk-switches": {
    ...CATEGORY_MANIFEST["netzwerk-switches"],
    description: "Ethernet-Verteiler",
    parent: "pc-komponenten",
    categoryType: "standard",
    imageUrl: "/images/category/network-switch.jpg",
    aliases: ["network-switches"],
  },
  netzwerkkarten: {
    ...CATEGORY_MANIFEST.netzwerkkarten,
    description: "WLAN-Karten",
    parent: "pc-komponenten",
    categoryType: "standard",
    aliases: ["network-cards"],
  },
  "kabel-adapter": {
    ...CATEGORY_MANIFEST["kabel-adapter"],
    description: "Verbindungen",
    parent: "elektroartikel",
    categoryType: "standard",
    aliases: ["cables"],
  },
  "laptop-staender": {
    ...CATEGORY_MANIFEST["laptop-staender"],
    description: "Halterungen",
    parent: "computer",
    categoryType: "standard",
    aliases: ["laptop-stands"],
  },
  "usv-anlagen": {
    ...CATEGORY_MANIFEST["usv-anlagen"],
    description: "Notstrom",
    parent: "pc-komponenten",
    categoryType: "standard",
    aliases: ["ups"],
  },
  kabelmanagement: {
    ...CATEGORY_MANIFEST.kabelmanagement,
    description: "Ordnung",
    parent: "pc-komponenten",
    categoryType: "standard",
    aliases: ["cable-management"],
  },
  monitorhalterungen: {
    ...CATEGORY_MANIFEST.monitorhalterungen,
    description: "Arme & Halter",
    parent: "computer",
    categoryType: "standard",
    aliases: ["monitor-arms"],
  },
  "schreibtisch-zubehoer": {
    ...CATEGORY_MANIFEST["schreibtisch-zubehoer"],
    description: "Ordnung am Tisch",
    parent: "computer",
    categoryType: "standard",
    aliases: ["desk-accessories"],
  },
  buerostuehle: {
    ...CATEGORY_MANIFEST.buerostuehle,
    description: "Ergonomie",
    parent: "computer",
    categoryType: "standard",
    aliases: ["office-chairs"],
  },
  stehschreibtische: {
    ...CATEGORY_MANIFEST.stehschreibtische,
    description: "Höhenverstellbar",
    parent: "computer",
    categoryType: "standard",
    aliases: ["standing-desks"],
  },
  "tablet-zubehoer": {
    ...CATEGORY_MANIFEST["tablet-zubehoer"],
    description: "Hüllen & Stifte",
    parent: "computer",
    categoryType: "standard",
    aliases: ["tablet-accessories"],
  },
  "handy-zubehoer": {
    ...CATEGORY_MANIFEST["handy-zubehoer"],
    description: "Schutz & Power",
    parent: "telekommunikation",
    categoryType: "standard",
    aliases: ["phone-accessories"],
  },
  "gamepad-controller": {
    ...CATEGORY_MANIFEST["gamepad-controller"],
    description: "Gamepads",
    parent: "gaming-elektrospielzeug",
    categoryType: "standard",
    imageUrl: "/images/category/game-controller.jpg",
    aliases: ["game-controllers"],
  },
  "vr-brillen": {
    ...CATEGORY_MANIFEST["vr-brillen"],
    description: "Virtual Reality",
    parent: "gaming-elektrospielzeug",
    categoryType: "standard",
    imageUrl: "/images/category/vr-glasses.jpg",
    aliases: ["vr-headsets"],
    popularFilters: [
      { label: "Meta Quest", params: "series=quest" },
      { label: "PlayStation VR2", params: "platform=ps5" },
    ],
  },
  mikrofone: {
    ...CATEGORY_MANIFEST.mikrofone,
    description: "Audio-Aufnahme",
    parent: "hifi-audio",
    categoryType: "standard",
    aliases: ["microphones"],
  },
  "gaming-stuehle": {
    ...CATEGORY_MANIFEST["gaming-stuehle"],
    description: "Zocker-Sessel",
    parent: "gaming-elektrospielzeug",
    categoryType: "standard",
    imageUrl: "/images/category/gaming-chair.jpg",
    aliases: ["gaming-chairs"],
    popularFilters: [
      { label: "Secretlab", params: "brand=Secretlab" },
      { label: "Noblechairs", params: "brand=Noblechairs" },
      { label: "Stoffbezug", params: "material=fabric" },
    ],
  },
  webcams: {
    name: "Webcams",
    description: "Videokonferenz",
    parent: "computer",
    categoryType: "standard",
  },
  "capture-karten": {
    ...CATEGORY_MANIFEST["capture-karten"],
    description: "Streaming-Hardware",
    parent: "pc-komponenten",
    categoryType: "standard",
    aliases: ["capture-cards"],
  },
  prozessoren: {
    ...CATEGORY_MANIFEST.prozessoren,
    description: "CPUs von Intel & AMD",
    parent: "pc-komponenten",
    categoryType: "analytical",
    imageUrl: "/images/category/cpu.jpg",
    aliases: ["cpu", "processors"],
    popularFilters: [
      { label: "Sockel AM5", params: "socket=AM5" },
      { label: "Sockel 1700", params: "socket=LGA1700" },
    ],
    filterGroups: [
      { label: "Hersteller", field: "brand", type: "checkbox" },
      { label: "Sockel", field: "socket", type: "checkbox" },
      { label: "Kerne", field: "cores", type: "checkbox" },
    ],
  },
  elektrowerkzeuge: {
    name: "Elektrowerkzeuge",
    description: "Bohren, Sägen & Schleifen",
    categoryType: "standard",
    imageUrl: "/images/category/power-tools.jpg",
    hidden: true,
  },
  akkuschrauber: {
    name: "Akkuschrauber",
    description: "Kabelloses Schrauben",
    parent: "elektrowerkzeuge",
    categoryType: "standard",
    imageUrl: "/images/category/drill.jpg",
    hidden: true,
    popularFilters: [
      { label: "Makita 18V", params: "series=18v" },
      { label: "Bosch Professional", params: "brand=Bosch+Professional" },
    ],
  },
  bohrmaschinen: {
    name: "Bohrmaschinen",
    description: "Schlag- & Hammerbohrer",
    parent: "elektrowerkzeuge",
    categoryType: "standard",
    imageUrl: "/images/category/hammer-drill.jpg",
    hidden: true,
  },
  kreissaegen: {
    name: "Kreissägen",
    description: "Hand- & Tischkreissägen",
    parent: "elektrowerkzeuge",
    categoryType: "standard",
    imageUrl: "/images/category/circular-saw.jpg",
    hidden: true,
    popularFilters: [
      { label: "Tauchsäge", params: "type=plunge" },
      { label: "Festool", params: "brand=Festool" },
    ],
  },
  schleifmaschinen: {
    name: "Schleifmaschinen",
    description: "Exzenter- & Winkelschleifer",
    parent: "elektrowerkzeuge",
    categoryType: "standard",
    imageUrl: "/images/category/sander.jpg",
    hidden: true,
  },
  fraesmaschinen: {
    name: "Fräsmaschinen",
    description: "Oberfräsen & Kantenfräsen",
    parent: "elektrowerkzeuge",
    categoryType: "standard",
    imageUrl: "/images/category/router-tool.jpg",
    hidden: true,
  },
  "3d-drucker": {
    name: "3D-Drucker",
    description: "3D-Drucker für Hobby und Industrie",
    parent: "drucker-scanner",
    categoryType: "standard",
    imageUrl: "/images/category/3d-printer.jpg",
    popularFilters: [
      { label: "Bambu Lab", params: "brand=Bambu+Lab" },
      { label: "Anycubic", params: "brand=Anycubic" },
      { label: "Creality", params: "brand=Creality" },
      { label: "Mehrfarbdruck", params: "features=multicolor" },
    ],
  },
  laserdrucker: {
    name: "Laserdrucker",
    description: "Schnelle und effiziente Laserdrucker",
    parent: "drucker-scanner",
    categoryType: "standard",
    imageUrl: "/images/category/laser-printer.jpg",
    popularFilters: [
      { label: "HP LaserJet", params: "brand=HP" },
      { label: "Brother", params: "brand=Brother" },
      { label: "Farblaserdrucker", params: "features=color" },
      { label: "WLAN", params: "features=wifi" },
    ],
  },
  kompaktkameras: {
    name: "Kompaktkameras",
    description: "Kleine Kameras für unterwegs",
    parent: "fotografie",
    categoryType: "standard",
    imageUrl: "/images/category/compact-camera.jpg",
    popularFilters: [
      { label: "Sony", params: "brand=Sony" },
      { label: "Canon", params: "brand=Canon" },
      { label: "Panasonic", params: "brand=Panasonic" },
      { label: "Vlogging", params: "type=vlogging" },
    ],
  },
};
