export interface LeanProduct {
  [key: string]: unknown;
  id?: number;
  slug?: string;
  asin?: string;
  price?: number;
  title?: string;
  modelTitle?: string;
  variantSuffix?: string;
  specificationsSource?: string | null;
  subtitle?: string;
  image?: string;
  pricePerUnit?: number;
  capacity?: number | null;
  capacityUnit?: string | null;
  formFactor?: string | null;
  brand?: string | null;
  rating?: number | null;
  reviewCount?: number | null;
  salesRank?: number | null;
  monthlySold?: number | null;
  variationAttributes?: string | null;
  isVariantGroup?: boolean;
  variantCount?: number;
  category?: string;
  listPrice?: number;
  savings?: number;
  isParentView?: boolean;
  canonicalId?: number | null;
  displayId?: number;
  officialTitle?: string | null;
  mpn?: string | null;
  category_id?: number | string;
  officialSpecifications?: Record<string, unknown> | string | null;
  specifications?: Record<string, unknown> | string | null;
}
