services:
  web:
    build:
      context: .
      target: runner
    container_name: cleverprices-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - /etc/dokploy/volumes/cleverprices/data:/app/data

  worker:
    build:
      context: .
      target: worker-runner
    container_name: cleverprices-worker
    restart: always
    # No ports exposed for the worker
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/dokploy/volumes/cleverprices/data:/app/data
