services:
  app:
    build: .
    container_name: cleverprices
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Mount the DB file if you want to update it without rebuilding (Optional)
    # volumes:
    #   - ./data/cleverprices.db:/app/data/cleverprices.db
